### ISSUE TITLE
VQA Example

### ISSUE THREAD

**Issue by superhans** [marcotcr/anchor#14]
Hi Marco,

Any pointers or code on a VQA example ? Any way to modify the Imagenet example for VQA ?

**Comment by marcotcr** [comment]
For the VQA example, the anchor was in terms of the question, so you should use `AnchorText`. You just have to wrap the prediction function so that it takes in a list of questions, e.g. assume the original predict proba function is `predict_proba(image, question)`, the wrapper would be something like:
```
new_predict = lambda questions: np.array([predict_proba(image, q) for q in questions])
```
