### ISSUE TITLE
The meaning of some notations in the paper

### ISSUE THREAD

**Issue by marcwww** [marcotcr/anchor#32]
Dear Prof. Marco,

I've been studying your anchor paper, and want to figure out some details.

1. For Eq.3:
![image](https://user-images.githubusercontent.com/10141302/65381374-5ec36100-dd22-11e9-9281-21387e1fd96f.png)
how to calculate this probability of probability? 
2. In Alg.1, function BestCand:
![image](https://user-images.githubusercontent.com/10141302/65381409-443db780-dd23-11e9-8fc1-4c085c2d825e.png)
what is the definition of this precision with delta?
![image](https://user-images.githubusercontent.com/10141302/65381426-82d37200-dd23-11e9-971a-518fefce7fbe.png)

Thanks a lot if you could do some explaining.

**Comment by marcotcr** [comment]
1. Note that prec is not a probability, it is an expectation (and thus a scalar). Rather than compute that probability,  equation 3 is saying we want to be able to lower bound it, so as to guarantee that our precision is at least as high as the threshold. To understand how this upper bound works, you may want to read about the UCB algorithm, as it is easier to get intuition about it than KL-LUCB (which we actually use)
2. prec_ub(A', delta) is the current upper bound on the precision of set A' given delta, i.e. it's an upper bound in the form of P(prec(A') <= X) >= 1 - delta

P.S. I'm not a professor : )
